// In-Memory Data Store & Supabase Sync Helper for Tiga Angkatan

export const store = {
  users: [
    {
      user_id: '00000000-0000-0000-0000-000000000001',
      name: 'Owner Tiga Angkatan',
      email: 'owner@tigaangkatan.id',
      role: 'owner',
      created_at: new Date().toISOString(),
    },
  ],

  products: [
    {
      product_id: 'prod-1',
      name: 'Iced Latte',
      price: 15000,
      category: 'Kopi',
      default_variant: 'Less Sugar, Ice',
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      product_id: 'prod-2',
      name: 'Americano',
      price: 18000,
      category: 'Kopi',
      default_variant: 'Hot / No Sugar',
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      product_id: 'prod-3',
      name: 'Cappuccino',
      price: 20000,
      category: 'Kopi',
      default_variant: 'Regular',
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      product_id: 'prod-4',
      name: 'Chocolate',
      price: 17000,
      category: 'Non-Kopi',
      default_variant: 'Ice',
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      product_id: 'prod-5',
      name: 'Matcha Latte',
      price: 20000,
      category: 'Non-Kopi',
      default_variant: 'Oatmilk',
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      product_id: 'prod-6',
      name: 'Croissant',
      price: 15000,
      category: 'Snack',
      default_variant: 'Butter',
      image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      product_id: 'prod-7',
      name: 'Avocado Toast',
      price: 25000,
      category: 'Makanan',
      default_variant: 'Sourdough',
      image_url: null,
      created_at: new Date().toISOString(),
    },
  ],

  stockItems: [
    {
      stock_id: 'sugar',
      name: 'Sugar',
      category: 'Gula & Pemanis',
      current_stock: 3.0,
      min_stock: 5.0,
      unit: 'kg',
      cost_per_unit: 16000,
      supplier: 'PT Sumber Manis Nusantara',
      note: 'Gula pasir kristal putih premium',
      updated_at: new Date().toISOString(),
    },
    {
      stock_id: 'fresh_milk',
      name: 'Fresh Milk',
      category: 'Susu & Dairy',
      current_stock: 5.0,
      min_stock: 8.0,
      unit: 'L',
      cost_per_unit: 24000,
      supplier: 'Greenfield Dairy Farm',
      note: 'Pasteurized Fresh Milk 1L per pack',
      updated_at: new Date().toISOString(),
    },
    {
      stock_id: 'coffee_beans',
      name: 'Coffee Beans',
      category: 'Biji Kopi',
      current_stock: 8.0,
      min_stock: 3.0,
      unit: 'kg',
      cost_per_unit: 95000,
      supplier: 'Aceh Gayo Specialty Roastery',
      note: 'House Blend 70% Arabica Gayo & 30% Robusta Temanggung',
      updated_at: new Date().toISOString(),
    },
    {
      stock_id: 'chocolate_syrup',
      name: 'Chocolate Syrup',
      category: 'Sirup & Perisa',
      current_stock: 6.0,
      min_stock: 2.0,
      unit: 'btl',
      cost_per_unit: 65000,
      supplier: 'Diva Flavor Indonesia',
      note: 'Botol 750ml rasa Dark Rich Chocolate',
      updated_at: new Date().toISOString(),
    },
    {
      stock_id: 'caramel_syrup',
      name: 'Caramel Syrup',
      category: 'Sirup & Perisa',
      current_stock: 1.5,
      min_stock: 2.0,
      unit: 'btl',
      cost_per_unit: 68000,
      supplier: 'Diva Flavor Indonesia',
      updated_at: new Date().toISOString(),
    },
    {
      stock_id: 'cup_16oz',
      name: 'Cup Plastic 16oz + Lid',
      category: 'Cup & Kemasan',
      current_stock: 45.0,
      min_stock: 100.0,
      unit: 'pcs',
      cost_per_unit: 850,
      supplier: 'Mitra Pack Tangerang',
      updated_at: new Date().toISOString(),
    },
  ],

  productRecipes: [
    { recipe_id: 'rec-1', product_id: 'prod-1', stock_id: 'coffee_beans', quantity_required: 0.018 },
    { recipe_id: 'rec-2', product_id: 'prod-1', stock_id: 'fresh_milk', quantity_required: 0.15 },
    { recipe_id: 'rec-3', product_id: 'prod-1', stock_id: 'sugar', quantity_required: 0.01 },
    { recipe_id: 'rec-4', product_id: 'prod-2', stock_id: 'coffee_beans', quantity_required: 0.02 },
  ],

  orders: [
    {
      order_id: 'ord-1001',
      order_code: '#3A-88895',
      user_id: '00000000-0000-0000-0000-000000000001',
      order_type: 'Dine In',
      table_number: '04',
      customer_name: 'Budi',
      subtotal: 45000,
      tax: 4500,
      total_amount: 49500,
      payment_method: 'QRIS / E-Wallet',
      cash_given: 0,
      change_amount: 0,
      status: 'PAID',
      created_at: new Date().toISOString(),
    },
  ],

  orderItems: [
    {
      order_item_id: 'item-1',
      order_id: 'ord-1001',
      product_id: 'prod-1',
      product_name: 'Iced Latte',
      variant: 'Less Sugar, Ice',
      quantity: 2,
      price_at_sale: 15000,
      subtotal: 30000,
      note: 'Extra ice',
    },
    {
      order_item_id: 'item-2',
      order_id: 'ord-1001',
      product_id: 'prod-6',
      product_name: 'Croissant',
      variant: 'Butter',
      quantity: 1,
      price_at_sale: 15000,
      subtotal: 15000,
      note: null,
    },
  ],

  stockLogs: [
    {
      log_id: 'log-1',
      stock_id: 'sugar',
      stock_name: 'Sugar',
      type: 'OUT',
      quantity: 2.0,
      unit: 'kg',
      source: 'POS',
      reference_code: '#3A-88895',
      operator_name: 'Kasir Budi',
      note: 'Penjualan minuman shift sore',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      log_id: 'log-2',
      stock_id: 'sugar',
      stock_name: 'Sugar',
      type: 'IN',
      quantity: 10.0,
      unit: 'kg',
      source: 'Restock / Pembelian',
      reference_code: '#PO-2026-08',
      operator_name: 'Owner',
      note: 'Pembelian stok grosir mingguan',
      created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
  ],

  financeTransactions: [
    {
      transaction_id: 'tx-001',
      user_id: '00000000-0000-0000-0000-000000000001',
      order_id: 'ord-1001',
      title: 'Iced Latte & Croissant Sales',
      type: 'INCOME',
      category: 'sales',
      amount: 49500,
      source: 'POS_AUTOMATIC',
      notes: 'Order #3A-88895',
      timestamp: new Date().toISOString(),
    },
    {
      transaction_id: 'tx-002',
      user_id: '00000000-0000-0000-0000-000000000001',
      order_id: null,
      title: 'Coffee Beans Purchase',
      type: 'EXPENSE',
      category: 'ingredients',
      amount: 250000,
      source: 'MANUAL',
      notes: 'Restock 2kg Espresso Blend dari Roastery Lokal',
      timestamp: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      transaction_id: 'tx-003',
      user_id: '00000000-0000-0000-0000-000000000001',
      order_id: null,
      title: 'Sugar Purchase',
      type: 'EXPENSE',
      category: 'ingredients',
      amount: 170000,
      source: 'MANUAL',
      notes: 'Gula Aren Cair 5 Jerigen',
      timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  ],

  aiMessages: [
    {
      message_id: 'msg-001',
      user_id: '00000000-0000-0000-0000-000000000001',
      sender: 'USER',
      text: 'Bagaimana bisnis saya hari ini?',
      type: 'text',
      extra_data: null,
      timestamp: new Date(Date.now() - 1800000).toISOString(),
    },
    {
      message_id: 'msg-002',
      user_id: '00000000-0000-0000-0000-000000000001',
      sender: 'AI',
      text: 'Kinerja bisnis hari ini tampak baik. Pendapatan telah mencapai Rp1.250.000, naik 12% dibandingkan kemarin.',
      type: 'businessSummary',
      extra_data: {
        revenue: 1250000.0,
        profit: 450000.0,
        bestSeller: 'Iced Latte',
      },
      timestamp: new Date(Date.now() - 1795000).toISOString(),
    },
  ],

  aiActions: [
    {
      action_id: 'act-001',
      message_id: 'msg-002',
      intent: 'ADD_STOCK_AND_EXPENSE',
      payload: {
        actionId: 'act-001',
        intent: 'ADD_STOCK_AND_EXPENSE',
        itemName: 'Sugar',
        quantity: 10,
        unit: 'kg',
        expenseAmount: 170000,
        category: 'Bahan Baku',
        status: 'confirmed',
      },
      status: 'CONFIRMED',
      created_at: new Date(Date.now() - 1795000).toISOString(),
    },
  ],
};
