name: AISISTENKU
description: Tiga Angkatan Mobile App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  fl_chart: ^1.2.0
  flutter_markdown: ^0.7.7+1
  socket_io_client: ^3.0.2
  flutter_esc_pos_utils: ^1.0.1
  blue_thermal_printer: ^1.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
